# To run do:
#
# docker-compose build
# docker-compose up -d web
#
db:
  # Note you cannot scale if you use conteiner_name
  container_name: db.maps.kartoza.com
  image: kartoza/postgis:9.4-2.1
  volumes:
    #- ./pg/postgres_data:/var/lib/postgresql
    - ./backups:/backups
  environment:
    - USERNAME=docker
    - PASS=docker
  restart: on-failure:5

btsync:
  image: kartoza/btsync
  container_name: btsync.maps.kartoza.com
  hostname: btsync.maps.kartoza.com
  volumes:
    - /web
  environment:
    # This should be the read only key
    - SECRET=BDPQXDNISWW2JR4IJTJWDXU3OMP3DSH5K
    - DEVICE=readonly-maps.maps.kartoza.com
  restart: on-failure:5

qgis-server:
  image: kartoza/qgis-server
  hostname: maps.kartoza.com
  container_name: maps.kartoza.com
  volumes_from: 
    - btsync
  volumes:
    - ./logs:/var/log/apache2
  links:
    - db:db
  ports:
    - 8198:80 
  restart: on-failure:5

